# Generated by Django 3.0.1 on 2019-12-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(max_length=256)),
                ('title', models.CharField(default='', max_length=126)),
                ('text', models.TextField()),
            ],
        ),
    ]
